### ISSUE TITLE
Integration with logstash-logger

### ISSUE THREAD

**Issue by dmakhmutov** [iMacTia/sidekiq-logstash#2]
Thanks for gem, can I integrate with https://github.com/dwbutler/logstash-logger, to send log to our elk server in any ways?

**Comment by iMacTia** [comment]
Hi @dmakhmutov,
that seems OK to me. `sidekiq-logstash` is not a logger after all, but just a formatter.
You can still set `Sidekiq.logger` to anything you want, i.e. an instance of `LogstashLogger`.
Please see Sidekiq [Logging](https://github.com/mperham/sidekiq/wiki/Logging#customize-logger) section for additional details on how to do this.
