### ISSUE TITLE
Missing 'retry_count'

### ISSUE THREAD

**Issue by eflorit** [iMacTia/sidekiq-logstash#24]
Hello, the README states that `retry_count` is one of the metrics tracked by the gem, however there doesn't seem to be any trace of it in the code. Was it removed at some point or was it never implemented? :thinking:

**Comment by iMacTia** [comment]
Hi @eflorit, the `retry_count` is not generated by this library, it's part of the job payload from Sidekiq itself (see the code [here](https://github.com/mperham/sidekiq/blob/main/lib/sidekiq/job_retry.rb#L152)).
Was this just a question to know how to interact with it, or is it missing from your logs?

**Comment by eflorit** [comment]
I was under the impression that this key was always present (and be `0` before any retry attempt) but I am realizing it only appears then starts incrementing on the second retry. Kind of counter intuitive but you're right it isn't related to this gem. Thank you for taking the time to reply and for maintaining this project. :)
