### ISSUE TITLE
`#log_job_exception` gets wrong exception info when job can be retried

### ISSUE THREAD

**Issue by yiichou** [iMacTia/sidekiq-logstash#28]
**Sidekiq version**: 6.4.1
**Rails version**: 6.0.3.6

If a failed job is able to be retried,  Sidekiq will 

1. catch the really exception 
2. append the exception message to the job and push it into `retry` queue
3. raise a new exception `Sidekiq::JobRetry::Skip`

So, when Sidekiq::LogstashJobLogger tries to parse the failed job by `#log_job_exception`,
the received exception is `Sidekiq::JobRetry::Skip`.

Finally, the recorded `error_message`, `error` and `error_backtrace` are wrong.

**Comment by yiichou** [comment]
I have a patch to solve this problem, it tries to get really exception message from the enqueued retry job

```ruby
def log_job_exception(job, started_at, exc)
        payload = setup_payload(job)

        payload['duration'] = elapsed(started_at)
        payload['message'] += ": fail: #{payload['duration']} sec"
        payload['job_status'] = 'fail'

        if exc.is_a? Sidekiq::JobRetry::Skip
          Sidekiq::RetrySet.new.scan(payload['jid'], 1) do |retried_job|
            payload['error_message'] = retried_job['error_message']
            payload['error_class'] = retried_job['error_class']
          end
        else
          payload['error_message'] = exc.message
          payload['error_class'] = exc.class
          payload['error_backtrace'] = %('#{exc.backtrace.join("\n")}')
        end

        process_payload(payload)
      end
```

**Comment by iMacTia** [comment]
Hi @yiichou, thanks for raising this.
I think I saw `Sidekiq::JobRetry::Skip` exceptions before, but they never posed to be a problem, this might be a combination of sidekiq/ruby/rails versions.

Do you think you might be able to come up with a PR that reproduces the issue so we can run it against all the CI matrix versions?

**Comment by yiichou** [comment]
https://github.com/iMacTia/sidekiq-logstash/pull/29
