### ISSUE TITLE
Undefined method `current_tags'

### ISSUE THREAD

**Issue by rkiller** [iMacTia/sidekiq-logstash#34]
Hi:

Thanks for the great gem. I've been getting a lot of errors:

NoMethodError: undefined method `current_tags' for #<Sidekiq::Logging::LogstashFormatter>

Any idea how to resolve this?

**Comment by iMacTia** [comment]
Hi @rkiller, thank you for using this gem 🙏 !
Would you be able to provide a stacktrace for the error above?
It would be interesting to see where this is coming from as we don't use `current_tags` in this repository

**Comment by iMacTia** [comment]
Closing for now due to lack of info, happy to reopen once more details are provided 👍
