### ISSUE TITLE
How can I log the json data only?

### ISSUE THREAD

**Issue by dfuentes77** [iMacTia/sidekiq-logstash#36]
My log entries look like this
```
I, [2022-11-30T08:22:59.387838 #1916970]  INFO -- : {"class"=>..."
```
but I just want to log that latter JSON block that logstash creates.  I just want the JSON in order to make it easier to ingest in logging services that auto parse only JSON.

Is there an easy way to do this in my sidekiq config?

**Comment by iMacTia** [comment]
@dfuentes77 you should not be seeing those blocks at the beginning, it's almost as if the formatter is not being configured properly.
Are you manually changing the sidekiq logger or sidekiq formatter anywhere in your application?
Can you log the `logger.inspect` from inside a worker to see what it looks like?

**Comment by dfuentes77** [comment]
Thank you for helping.  I appreciate it greatly.

For some background, here are the version of gems I'm running ( in case that matters )
```
sidekiq (5.1.3)
sidekiq-logstash (1.2.1)
logstash-event (1.2.02)
```

I went through my config and couldn't find anywhere where it's changing the formatter

As for the **sidekiq.rb**, I literally have this at the top:
```
Sidekiq::Logstash.setup
```
and this in the `Sidekiq.configure_server` block:
```
  config.logger = Logger.new(Rails.root.join('log', 'sidekiq.log'))
```

Regarding your suggestion, I've tried adding the `logger.inspect` all over inside the job and I'm not seeing any extra log output/fields to help with troubleshooting.  I tried setting log level to debug in the server block:
```
config.logger.level = Logger::DEBUG
```
I even tried [this config for per worker log level (debug)](https://github.com/mperham/sidekiq/wiki/Logging#per-worker-log-level) but it didn't help either.

Thanks for your help!

**Comment by dfuentes77** [comment]
Also, separately and this might seem like a dumb question but is there way to make the logstash JSON block fully valid JSON.  I'm trying to have it ingested by Datadog logging service and since it's not valid JSON (w/ the `=>`), they won't ingest it as JSON.  They can ingest it as a key:value format but then the `args` fields don't come through.  Let me know if you have any idea on how to make it fully valid JSON or is that just not possible or makes sense with logstash formatting it the way it does.  Thank you!

example log entry
```
I, [2022-12-07T18:13:38.550211 #677167]  INFO -- : {"class"=>"V3::worker", "args"=>["<number>", {"set_ids"=>["<number>"], "course_ids"=>""}], "retry"=>true, "queue"=>"eventually_light", "log_level"=>"debug", "unique"=>"while_executing", "jid"=>"<jobid>", "created_at"=>"2022-12-07T18:09:25.292Z", "lock_timeout"=>0, "lock_expiration"=>nil, "unique_prefix"=>"uniquejobs", "unique_args"=>["<number>", {"set_ids"=>["<number>"], "course_ids"=>""}], "unique_digest"=>"uniquejobs:<digest>:RUN", "enqueued_at"=>"2022-12-07T18:09:25.292Z", "message"=>"V3::worker JID-e8320733e5fd7ee14f1241a6: done: 70.123 sec", "pid"=>677167, "duration"=>70.123, "job_status"=>"done", "completed_at"=>"2022-12-07T18:13:38.550Z"}
```

**Comment by dfuentes77** [comment]
Thank you for all the help.  

It looks like it was the way I was specifying the logger w/ `config.logger = Logger.new(...` that was setting the logger to a format I didn't want.  If I let it just go straight to stdout, it outputs just the proper JSON and that's all.  I wish there was a way to set Sidekiq to log what it logs to stdout to a specified file, but so far I can't seem to find a way to do that.  If you do know of a way, please let me know.  If you don't, feel free to close this issue.  Thanks again!

**Comment by iMacTia** [comment]
Glad things are working now!

Based on what you observed above, I suspect the problem what that you were changing the `sidekiq.logger` AFTER `Sidekiq::Logstash` setup. Since we change the logger formatter during setup (see [this line](https://github.com/iMacTia/sidekiq-logstash/blob/master/lib/sidekiq/logstash.rb#L38)), changing the logger afterward would effectively revert the change.

It's hard to tell for sure but I THINK that if you move your call to `Sidekiq::Logstash.setup` AFTER the `config.logger = Logger.new(Rails.root.join('log', 'sidekiq.log'))`, you should be able to get proper logging and formatting 👍

**Comment by dfuentes77** [comment]
I'm sorry I didn't update this sooner but that did work.  Thank you for your help!
